"""init

Revision ID: 7c9cdc4a84c6
Revises: 
Create Date: 2026-03-12 02:35:42.685763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c9cdc4a84c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_log',
    sa.Column('backup_log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('backup_time', sa.DateTime(), nullable=False),
    sa.Column('backup_file', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('backup_log_id')
    )
    op.create_table('biblio',
    sa.Column('biblio_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gmd_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('sor', sa.String(length=200), nullable=True),
    sa.Column('edition', sa.String(length=50), nullable=True),
    sa.Column('isbn_issn', sa.String(length=32), nullable=True),
    sa.Column('publisher_id', sa.Integer(), nullable=True),
    sa.Column('publish_year', sa.String(length=20), nullable=True),
    sa.Column('collation', sa.String(length=100), nullable=True),
    sa.Column('series_title', sa.String(length=200), nullable=True),
    sa.Column('call_number', sa.String(length=50), nullable=True),
    sa.Column('language_id', sa.String(length=5), nullable=True),
    sa.Column('source', sa.String(length=3), nullable=True),
    sa.Column('publish_place_id', sa.Integer(), nullable=True),
    sa.Column('classification', sa.String(length=40), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=100), nullable=True),
    sa.Column('file_att', sa.String(length=255), nullable=True),
    sa.Column('opac_hide', sa.SmallInteger(), nullable=True),
    sa.Column('promoted', sa.SmallInteger(), nullable=True),
    sa.Column('labels', sa.Text(), nullable=True),
    sa.Column('frequency_id', sa.Integer(), nullable=False),
    sa.Column('spec_detail_info', sa.Text(), nullable=True),
    sa.Column('content_type_id', sa.Integer(), nullable=True),
    sa.Column('media_type_id', sa.Integer(), nullable=True),
    sa.Column('carrier_type_id', sa.Integer(), nullable=True),
    sa.Column('input_date', sa.DateTime(), nullable=True),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('biblio_id')
    )
    with op.batch_alter_table('biblio', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_biblio_classification'), ['classification'], unique=False)
        batch_op.create_index(batch_op.f('ix_biblio_gmd_id'), ['gmd_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_biblio_uid'), ['uid'], unique=False)

    op.create_table('biblio_attachment',
    sa.Column('biblio_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('placement', sa.Enum('link', 'popup', 'embed'), nullable=True),
    sa.Column('access_type', sa.Enum('public', 'private'), nullable=False),
    sa.Column('access_limit', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('biblio_id', 'file_id')
    )
    op.create_table('biblio_author',
    sa.Column('biblio_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('biblio_id', 'author_id')
    )
    op.create_table('biblio_custom',
    sa.Column('biblio_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('biblio_id')
    )
    op.create_table('biblio_relation',
    sa.Column('biblio_id', sa.Integer(), nullable=False),
    sa.Column('rel_biblio_id', sa.Integer(), nullable=False),
    sa.Column('rel_type', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('biblio_id', 'rel_biblio_id')
    )
    op.create_table('biblio_topic',
    sa.Column('biblio_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('biblio_id', 'topic_id')
    )
    op.create_table('content',
    sa.Column('content_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content_title', sa.String(length=255), nullable=False),
    sa.Column('content_desc', sa.Text(), nullable=False),
    sa.Column('content_path', sa.String(length=20), nullable=False),
    sa.Column('is_news', sa.SmallInteger(), nullable=True),
    sa.Column('input_date', sa.DateTime(), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('content_id'),
    sa.UniqueConstraint('content_path')
    )
    op.create_table('files',
    sa.Column('file_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_title', sa.Text(), nullable=False),
    sa.Column('file_name', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('uploader_id', sa.Integer(), nullable=False),
    sa.Column('input_date', sa.DateTime(), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('file_id')
    )
    op.create_table('fines',
    sa.Column('fines_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fines_date', sa.Date(), nullable=False),
    sa.Column('member_id', sa.String(length=20), nullable=False),
    sa.Column('debet', sa.Integer(), nullable=True),
    sa.Column('credit', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('fines_id')
    )
    with op.batch_alter_table('fines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fines_member_id'), ['member_id'], unique=False)

    op.create_table('item',
    sa.Column('item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('biblio_id', sa.Integer(), nullable=True),
    sa.Column('call_number', sa.String(length=50), nullable=True),
    sa.Column('coll_type_id', sa.Integer(), nullable=True),
    sa.Column('item_code', sa.String(length=20), nullable=True),
    sa.Column('inventory_code', sa.String(length=200), nullable=True),
    sa.Column('received_date', sa.Date(), nullable=True),
    sa.Column('supplier_id', sa.String(length=6), nullable=True),
    sa.Column('order_no', sa.String(length=20), nullable=True),
    sa.Column('location_id', sa.String(length=3), nullable=True),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.Column('item_status_id', sa.String(length=3), nullable=True),
    sa.Column('site', sa.String(length=50), nullable=True),
    sa.Column('source', sa.Integer(), nullable=False),
    sa.Column('invoice', sa.String(length=20), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('price_currency', sa.String(length=10), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('input_date', sa.DateTime(), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('item_id'),
    sa.UniqueConstraint('item_code')
    )
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_biblio_id'), ['biblio_id'], unique=False)

    op.create_table('loan',
    sa.Column('loan_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_code', sa.String(length=20), nullable=True),
    sa.Column('member_id', sa.String(length=20), nullable=True),
    sa.Column('loan_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('renewed', sa.Integer(), nullable=False),
    sa.Column('loan_rules_id', sa.Integer(), nullable=False),
    sa.Column('actual', sa.Date(), nullable=True),
    sa.Column('is_lent', sa.Integer(), nullable=False),
    sa.Column('is_return', sa.Integer(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.Column('input_date', sa.DateTime(), nullable=True),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('loan_id')
    )
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loan_item_code'), ['item_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_loan_member_id'), ['member_id'], unique=False)

    op.create_table('member',
    sa.Column('member_id', sa.String(length=20), nullable=False),
    sa.Column('member_name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.Integer(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('member_type_id', sa.Integer(), nullable=True),
    sa.Column('member_address', sa.String(length=255), nullable=True),
    sa.Column('member_mail_address', sa.String(length=255), nullable=True),
    sa.Column('member_email', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('inst_name', sa.String(length=100), nullable=True),
    sa.Column('is_new', sa.Integer(), nullable=True),
    sa.Column('member_image', sa.String(length=200), nullable=True),
    sa.Column('pin', sa.String(length=50), nullable=True),
    sa.Column('member_phone', sa.String(length=50), nullable=True),
    sa.Column('member_fax', sa.String(length=50), nullable=True),
    sa.Column('member_since_date', sa.Date(), nullable=True),
    sa.Column('register_date', sa.Date(), nullable=True),
    sa.Column('expire_date', sa.Date(), nullable=False),
    sa.Column('member_notes', sa.Text(), nullable=True),
    sa.Column('is_pending', sa.SmallInteger(), nullable=False),
    sa.Column('mpasswd', sa.String(length=64), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=20), nullable=True),
    sa.Column('input_date', sa.Date(), nullable=True),
    sa.Column('last_update', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('member_id')
    )
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_member_member_name'), ['member_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_member_member_type_id'), ['member_type_id'], unique=False)

    op.create_table('member_custom',
    sa.Column('member_id', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('member_id')
    )
    op.create_table('mst_author',
    sa.Column('author_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('author_name', sa.String(length=100), nullable=False),
    sa.Column('author_year', sa.String(length=20), nullable=True),
    sa.Column('authority_type', sa.Enum('p', 'o', 'c'), nullable=True),
    sa.Column('auth_list', sa.String(length=20), nullable=True),
    sa.Column('input_date', sa.Date(), nullable=False),
    sa.Column('last_update', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('author_id')
    )
    op.create_table('mst_carrier_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('carrier_type', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=5), nullable=False),
    sa.Column('code2', sa.String(length=1), nullable=False),
    sa.Column('input_date', sa.DateTime(), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('carrier_type')
    )
    with op.batch_alter_table('mst_carrier_type', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mst_carrier_type_code'), ['code'], unique=False)

    op.create_table('mst_coll_type',
    sa.Column('coll_type_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('coll_type_name', sa.String(length=30), nullable=False),
    sa.Column('input_date', sa.Date(), nullable=True),
    sa.Column('last_update', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('coll_type_id'),
    sa.UniqueConstraint('coll_type_name')
    )
    op.create_table('mst_content_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=5), nullable=False),
    sa.Column('code2', sa.String(length=1), nullable=False),
    sa.Column('input_date', sa.DateTime(), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_type')
    )
    with op.batch_alter_table('mst_content_type', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mst_content_type_code'), ['code'], unique=False)

    op.create_table('mst_frequency',
    sa.Column('frequency_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('frequency', sa.String(length=25), nullable=False),
    sa.Column('language_prefix', sa.String(length=5), nullable=True),
    sa.Column('time_increment', sa.SmallInteger(), nullable=True),
    sa.Column('time_unit', sa.Enum('day', 'week', 'month', 'year'), nullable=True),
    sa.Column('input_date', sa.Date(), nullable=False),
    sa.Column('last_update', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('frequency_id')
    )
    op.create_table('mst_gmd',
    sa.Column('gmd_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gmd_code', sa.String(length=3), nullable=True),
    sa.Column('gmd_name', sa.String(length=30), nullable=False),
    sa.Column('icon_image', sa.String(length=100), nullable=True),
    sa.Column('input_date', sa.Date(), nullable=False),
    sa.Column('last_update', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('gmd_id'),
    sa.UniqueConstraint('gmd_code'),
    sa.UniqueConstraint('gmd_name')
    )
    op.create_table('mst_item_status',
    sa.Column('item_status_id', sa.String(length=3), nullable=False),
    sa.Column('item_status_name', sa.String(length=30), nullable=False),
    sa.Column('rules', sa.String(length=255), nullable=True),
    sa.Column('no_loan', sa.SmallInteger(), nullable=False),
    sa.Column('skip_stock_take', sa.SmallInteger(), nullable=False),
    sa.Column('input_date', sa.Date(), nullable=True),
    sa.Column('last_update', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('item_status_id'),
    sa.UniqueConstraint('item_status_name')
    )
    op.create_table('mst_label',
    sa.Column('label_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('label_name', sa.String(length=20), nullable=False),
    sa.Column('label_desc', sa.String(length=50), nullable=True),
    sa.Column('label_image', sa.String(length=200), nullable=False),
    sa.Column('input_date', sa.Date(), nullable=False),
    sa.Column('last_update', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('label_id'),
    sa.UniqueConstraint('label_name')
    )
    op.create_table('mst_language',
    sa.Column('language_id', sa.String(length=5), nullable=False),
    sa.Column('language_name', sa.String(length=20), nullable=False),
    sa.Column('input_date', sa.Date(), nullable=True),
    sa.Column('last_update', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('language_id'),
    sa.UniqueConstraint('language_name')
    )
    op.create_table('mst_loan_rules',
    sa.Column('loan_rules_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('member_type_id', sa.Integer(), nullable=False),
    sa.Column('coll_type_id', sa.Integer(), nullable=True),
    sa.Column('gmd_id', sa.Integer(), nullable=True),
    sa.Column('loan_limit', sa.Integer(), nullable=True),
    sa.Column('loan_periode', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('loan_rules_id')
    )
    op.create_table('mst_media_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('media_type', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=5), nullable=False),
    sa.Column('code2', sa.String(length=1), nullable=False),
    sa.Column('input_date', sa.DateTime(), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('media_type')
    )
    with op.batch_alter_table('mst_media_type', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mst_media_type_code'), ['code'], unique=False)

    op.create_table('mst_member_type',
    sa.Column('member_type_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('member_type_name', sa.String(length=50), nullable=False),
    sa.Column('loan_limit', sa.Integer(), nullable=False),
    sa.Column('loan_periode', sa.Integer(), nullable=False),
    sa.Column('member_periode', sa.Integer(), nullable=False),
    sa.Column('fine_each_day', sa.Integer(), nullable=False),
    sa.Column('input_date', sa.Date(), nullable=False),
    sa.Column('last_update', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('member_type_id'),
    sa.UniqueConstraint('member_type_name')
    )
    op.create_table('mst_place',
    sa.Column('place_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('place_name', sa.String(length=30), nullable=False),
    sa.Column('input_date', sa.Date(), nullable=True),
    sa.Column('last_update', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('place_id'),
    sa.UniqueConstraint('place_name')
    )
    op.create_table('mst_publisher',
    sa.Column('publisher_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('publisher_name', sa.String(length=100), nullable=False),
    sa.Column('input_date', sa.Date(), nullable=True),
    sa.Column('last_update', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('publisher_id'),
    sa.UniqueConstraint('publisher_name')
    )
    op.create_table('mst_supplier',
    sa.Column('supplier_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('supplier_name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=14), nullable=True),
    sa.Column('contact', sa.String(length=30), nullable=True),
    sa.Column('input_date', sa.Date(), nullable=True),
    sa.Column('last_update', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('supplier_id'),
    sa.UniqueConstraint('supplier_name')
    )
    op.create_table('mst_topic',
    sa.Column('topic_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('topic', sa.String(length=50), nullable=False),
    sa.Column('topic_type', sa.Enum('t', 'g', 'n', 'tm', 'gr', 'oc'), nullable=False),
    sa.Column('auth_list', sa.String(length=20), nullable=True),
    sa.Column('classification', sa.String(length=50), nullable=False),
    sa.Column('input_date', sa.Date(), nullable=True),
    sa.Column('last_update', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('topic_id')
    )
    op.create_table('plugins',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reserve',
    sa.Column('reserve_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.String(length=20), nullable=False),
    sa.Column('biblio_id', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.String(length=20), nullable=False),
    sa.Column('reserve_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('reserve_id')
    )
    with op.batch_alter_table('reserve', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reserve_item_code'), ['item_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_reserve_member_id'), ['member_id'], unique=False)

    op.create_table('search_biblio',
    sa.Column('biblio_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('author', sa.Text(), nullable=True),
    sa.Column('topic', sa.Text(), nullable=True),
    sa.Column('publisher', sa.String(length=100), nullable=True),
    sa.Column('publish_year', sa.String(length=20), nullable=True),
    sa.Column('call_number', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('biblio_id')
    )
    op.create_table('setting',
    sa.Column('setting_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('setting_name', sa.String(length=30), nullable=False),
    sa.Column('setting_value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('setting_id'),
    sa.UniqueConstraint('setting_name')
    )
    op.create_table('system_log',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('log_type', sa.Enum('staff', 'member', 'system'), nullable=False),
    sa.Column('id', sa.String(length=50), nullable=True),
    sa.Column('log_location', sa.String(length=50), nullable=False),
    sa.Column('sub_module', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=True),
    sa.Column('log_msg', sa.Text(), nullable=False),
    sa.Column('log_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('realname', sa.String(length=100), nullable=False),
    sa.Column('passwd', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('groups', sa.String(length=200), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user_group',
    sa.Column('group_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_name', sa.String(length=30), nullable=False),
    sa.Column('input_date', sa.Date(), nullable=True),
    sa.Column('last_update', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('group_id'),
    sa.UniqueConstraint('group_name')
    )
    op.create_table('visitor_count',
    sa.Column('visitor_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.String(length=20), nullable=True),
    sa.Column('member_name', sa.String(length=255), nullable=False),
    sa.Column('institution', sa.String(length=100), nullable=True),
    sa.Column('checkin_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('visitor_id')
    )
    with op.batch_alter_table('visitor_count', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visitor_count_member_id'), ['member_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor_count', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visitor_count_member_id'))

    op.drop_table('visitor_count')
    op.drop_table('user_group')
    op.drop_table('user')
    op.drop_table('system_log')
    op.drop_table('setting')
    op.drop_table('search_biblio')
    with op.batch_alter_table('reserve', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reserve_member_id'))
        batch_op.drop_index(batch_op.f('ix_reserve_item_code'))

    op.drop_table('reserve')
    op.drop_table('plugins')
    op.drop_table('mst_topic')
    op.drop_table('mst_supplier')
    op.drop_table('mst_publisher')
    op.drop_table('mst_place')
    op.drop_table('mst_member_type')
    with op.batch_alter_table('mst_media_type', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mst_media_type_code'))

    op.drop_table('mst_media_type')
    op.drop_table('mst_loan_rules')
    op.drop_table('mst_language')
    op.drop_table('mst_label')
    op.drop_table('mst_item_status')
    op.drop_table('mst_gmd')
    op.drop_table('mst_frequency')
    with op.batch_alter_table('mst_content_type', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mst_content_type_code'))

    op.drop_table('mst_content_type')
    op.drop_table('mst_coll_type')
    with op.batch_alter_table('mst_carrier_type', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mst_carrier_type_code'))

    op.drop_table('mst_carrier_type')
    op.drop_table('mst_author')
    op.drop_table('member_custom')
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_member_member_type_id'))
        batch_op.drop_index(batch_op.f('ix_member_member_name'))

    op.drop_table('member')
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loan_member_id'))
        batch_op.drop_index(batch_op.f('ix_loan_item_code'))

    op.drop_table('loan')
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_biblio_id'))

    op.drop_table('item')
    with op.batch_alter_table('fines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fines_member_id'))

    op.drop_table('fines')
    op.drop_table('files')
    op.drop_table('content')
    op.drop_table('biblio_topic')
    op.drop_table('biblio_relation')
    op.drop_table('biblio_custom')
    op.drop_table('biblio_author')
    op.drop_table('biblio_attachment')
    with op.batch_alter_table('biblio', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_biblio_uid'))
        batch_op.drop_index(batch_op.f('ix_biblio_gmd_id'))
        batch_op.drop_index(batch_op.f('ix_biblio_classification'))

    op.drop_table('biblio')
    op.drop_table('backup_log')
    # ### end Alembic commands ###
